# Site settings
title: Digital Footprint for Software Engineers
description: A practical playbook for engineers who want their work to be seen. Build a strong, authentic digital footprint using GitHub, LinkedIn, blogs, portfolios, and community work. Get your copy on Amazon.
author: Vinit Shahdeo
email: vinitshahdeo@gmail.com

# Social
twitter_username: Vinit_Shahdeo
github_username: vinitshahdeo
linkedin_username: vinitshahdeo

# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# SEO
social:
  name: Vinit Shahdeo
  links:
    - https://twitter.com/Vinit_Shahdeo
    - https://www.linkedin.com/in/vinitshahdeo
    - https://github.com/vinitshahdeo
